# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cezar.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 17);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.InputWords = QtWidgets.QLabel(self.centralwidget)
        self.InputWords.setGeometry(QtCore.QRect(220, 140, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.InputWords.setFont(font)
        self.InputWords.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(36, 36, 36);")
        self.InputWords.setObjectName("InputWords")
        self.Inputkey = QtWidgets.QLabel(self.centralwidget)
        self.Inputkey.setGeometry(QtCore.QRect(220, 218, 361, 22))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Inputkey.setFont(font)
        self.Inputkey.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(36, 36, 36);\n"
"text-align: center;")
        self.Inputkey.setObjectName("Inputkey")
        self.PutZaWord = QtWidgets.QLabel(self.centralwidget)
        self.PutZaWord.setGeometry(QtCore.QRect(40, 390, 331, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.PutZaWord.setFont(font)
        self.PutZaWord.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(36, 36, 36);")
        self.PutZaWord.setObjectName("PutZaWord")
        self.PutRaWord = QtWidgets.QLabel(self.centralwidget)
        self.PutRaWord.setGeometry(QtCore.QRect(430, 390, 331, 22))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.PutRaWord.setFont(font)
        self.PutRaWord.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(36, 36, 36);")
        self.PutRaWord.setObjectName("PutRaWord")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, -10, 801, 81))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(26, 26, 54);\n"
"background-color: rgb(163, 163, 163);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(245, 224, 176, 255), stop:0.09 rgba(246, 189, 237, 255), stop:0.14 rgba(194, 207, 246, 255), stop:0.19 rgba(184, 160, 168, 255), stop:0.25 rgba(171, 186, 248, 255), stop:0.32 rgba(243, 248, 224, 255), stop:0.385 rgba(249, 162, 183, 255), stop:0.47 rgba(100, 115, 124, 255), stop:0.58 rgba(251, 205, 202, 255), stop:0.65 rgba(170, 128, 185, 255), stop:0.75 rgba(252, 222, 204, 255), stop:0.805 rgba(206, 122, 218, 255), stop:0.86 rgba(254, 223, 175, 255), stop:0.91 rgba(254, 236, 244, 255), stop:1 rgba(255, 191, 221, 255));\n"
"")
        self.label_5.setObjectName("label_5")
        self.input1 = QtWidgets.QLineEdit(self.centralwidget)
        self.input1.setGeometry(QtCore.QRect(230, 170, 351, 30))
        self.input1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input1.setText("")
        self.input1.setObjectName("input1")
        self.input2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input2.setGeometry(QtCore.QRect(230, 240, 351, 30))
        self.input2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input2.setText("")
        self.input2.setObjectName("input2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(350, 320, 91, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color:blue;\n"
"font-size:14px;\n"
"font-weight:Bold;\n"
"border:none;\n"
"text-align:center;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(0, 255, 255);\n"
"}\n"
"QPushButton:Pressed{\n"
"background-color: white;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 410, 331, 101))
        self.label.setStyleSheet("background-color: rgb(212, 215, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(430, 410, 331, 101))
        self.label_2.setStyleSheet("background-color: rgb(212, 215, 255);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.InputWords.setText(_translate("MainWindow", " Вводите Ваш шедевр"))
        self.Inputkey.setText(_translate("MainWindow", " Bведите ключ"))
        self.PutZaWord.setText(_translate("MainWindow", "Зашифрованное слово"))
        self.PutRaWord.setText(_translate("MainWindow", "Расшифровка"))
        self.label_5.setText(_translate("MainWindow", "                          ШИФР ЦЕЗАРЯ"))
        self.pushButton.setText(_translate("MainWindow", "Действие"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
